### ISSUE TITLE
Add „Actions“ label

### ISSUE THREAD

**Issue by staabm** [Nyholm/roave-bc-check-docker#1]
Please label this repo as „Actions“ to make it discoverable via https://github.com/marketplace?type=actions

**Comment by Nyholm** [comment]
Hm. I did not know about that. 
Thank you. 

I added the "topic" on the project now. Does it work?

**Comment by staabm** [comment]
After some more research I guess what you need is a actions.yml
https://twitter.com/GHchangelog/status/1182365858770964481?s=20

**Comment by staabm** [comment]
confirmed, works :)
