### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by greg0ire** [Nyholm/roave-bc-check-docker#13]
I'm getting the following message on doctrine/inflector:

> Your requirements could not be resolved to an installable set of packages.

See https://github.com/doctrine/inflector/pull/177/checks#step:5:11

The fact that `--quiet` is used make this hard to troubleshoot: https://github.com/Nyholm/roave-bc-check-docker/blob/e0fb01ede9ea3a42303a4e283c3c63eaef5d5d58/gh-action/entrypoint.sh#L10

**Comment by Nyholm** [comment]
Now when #14 is merged. I assume this can be debugged more easily.

**Comment by Nyholm** [comment]
Please reopen if the error still exists

**Comment by greg0ire** [comment]
I'm still getting the error: https://github.com/doctrine/inflector/pull/173/checks?check_run_id=1317601616

But this time I can debug it easily, I think it's just a matter of upgrading the CS lib.

**Comment by Nyholm** [comment]
Oh, Yeah. You are correct. 

> dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0]

[Version 0.7.0](https://packagist.org/packages/dealerdirect/phpcodesniffer-composer-installer#v0.7.0) supports composer 2.

**Comment by Nyholm** [comment]
Sorry about breaking it like that.

**Comment by greg0ire** [comment]
No worries, the fix is in progress: https://github.com/doctrine/inflector/pull/179 :)
