### ISSUE TITLE
Composer 2

### ISSUE THREAD

**Issue by MGatner** [Nyholm/roave-bc-check-docker#20]
Getting:

> Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2

Would it be easy to update Composer?

**Comment by ktomk** [comment]
@MGatner: Wondered about it as well, but it is independent to the docker image, that just uses the utility, the utility installs composer and chooses to do so in version 1.x.

So unless the docker image does not ship with a rbcc version that does support composer 2 you will see this message.

> Would it be easy to update Composer?

This is perhaps a question to ask in the utility repository.

**Comment by Nyholm** [comment]
Composer 2 should be working now. All images have been updated
